export default [
    {
      name: 'MINDCAST 027 by Dextro',
      description: 'Started his career back in 1991, with regular releases for Suara, Odd, Matéria, Planet Rhythm, Unknown Territory, Korpus 9, Naked Lunch and Dolma, DJ Dextro became one of the pioneers on the Portugal Techno scene and one of our favourite artists. Being actively producing, he recently released his album "Aliens In My Backyard" via Naked Lunch Records and the name was surely not chosen by accident. It\'s an honour for us to welcome Dextro for MINDCAST 027.',
      css: 'linear-gradient(to top, #eb8034 0%, #4ceb34 100%)',
      cover: 'Cover_MINDCAST027.jpg',
      frame: '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/804520477&color=%23ff5500&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/hvmdmusic" title="HIVEMIND" target="_blank" style="color: #cccccc; text-decoration: none;">HIVEMIND</a> · <a href="https://soundcloud.com/hvmdmusic/mindcast-027-by-dextro" title="MINDCAST 027 by Dextro" target="_blank" style="color: #cccccc; text-decoration: none;">MINDCAST 027 by Dextro</a></div>',
      height: 300,
    },
    {
      name: 'MINDCAST 026 by TEDKA',
      description: 'TEDKA is another talent that we present on MINDCAST. After a several listenings to the music she\'s playing, we were convinced that her style varies through a lot of different sounds including everything from EBM to Techno, which makes her sets a very interesting experience, which will definitely make your staying at home very nice. Stay safe!',
      css: 'linear-gradient(135deg, #3452eb 0%, #ebc334 100%)',
      cover: 'Cover_MINDCAST026.jpg',
      frame: '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/794335699&color=%23ff5500&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/hvmdmusic" title="HIVEMIND" target="_blank" style="color: #cccccc; text-decoration: none;">HIVEMIND</a> · <a href="https://soundcloud.com/hvmdmusic/mindcast-026-by-tedka" title="MINDCAST 026 by TEDKA" target="_blank" style="color: #cccccc; text-decoration: none;">MINDCAST 026 by TEDKA</a></div>',
      height: 300,
    },
    {
      name: 'MINDCAST 025 by stndrd',
      description: 'Portugal born, currently based in Barcelona, stndrd got our attention with his mind blowing productions and sets. From the moment we got in touch with him, it was clear that we are working on the same frequencies, sharing a common goal - the quality music. He has succeeded to create his own, full of emotions and intensity sound that provides an incomparable feeling to the listener - something which in itself is really special, and our crew is happy to collaborate with such a great artist.',
      css: 'linear-gradient(120deg, #4ceb34 0%, #ebe834 100%)',
      cover: 'Cover_MINDCAST025_site.jpg',
      frame: '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/783767008&color=%23ff5500&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/hvmdmusic" title="HIVEMIND" target="_blank" style="color: #cccccc; text-decoration: none;">HIVEMIND</a> · <a href="https://soundcloud.com/hvmdmusic/mindcast-025-by-stndrd" title="MINDCAST 025 by stndrd" target="_blank" style="color: #cccccc; text-decoration: none;">MINDCAST 025 by stndrd</a></div>',
      height: 300,
    },
    {
      name: 'MINDCAST 024 Pvrvllel',
      description: 'Pvrvllel is the other half of PvrvllelSelf, who we presented to you earlier in MINDCAST. He differs with more ambient approach in order to build a ghost sounds atmosphere with the same uncompromised, live created sound of the duo, which does not fit in any musical boundaries. We are pretty sure that you will hear a lot about these guys in the near future, as they are one of the best live performers we heard recently!',
      css: 'linear-gradient(120deg, #34eb40 0%, #eb6234 100%)',
      cover: 'Cover_MINDCAST024.jpg',
      frame: '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/767478487&color=%23ff5500&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/hvmdmusic" title="HIVEMIND" target="_blank" style="color: #cccccc; text-decoration: none;">HIVEMIND</a> · <a href="https://soundcloud.com/hvmdmusic/mindcast-023-by-boryana" title="MINDCAST 023 by Boryana" target="_blank" style="color: #cccccc; text-decoration: none;">MINDCAST 023 by Boryana</a></div>',
      height: 300,
    },
    {
      name: 'MINDCAST 023 by Boryana',
      description: 'We can proudly say that Boryana is one of the most successful Bulgarian artists. Her uncompromising dark sound brings her to Sian’s Octopus Black Label, which became a synonym for a proper Techno sound for the last decade. With her regular releases for the imprint, Boryana got her fundamental place in it and takes part of the label showcases around the world at events like Winter Music Conference in Miami and BPM Festival in Mexico, alongside names such as Sian himself, Julian Jeweil and Pleasurekraft. She also performed at the legendary Ministry of Sound London, TRADE, and got her music released not only via Octopus Black, but on Mb Electronic (Marco Bailey), Waveform Recording (Victor Calderone), Never Ending (Citizen Kain). She left her trace on the local scene too with a memorable gigs at Mania, Cacao Beach, etc., and releases on Balthazar and Jackrock’s Renesanz Records.',
      css: 'linear-gradient(120deg, #eb34b1 0%, #eb8c34 100%)',
      cover: 'Cover_MINDCAST023.jpg',
      frame: '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/767478487&color=%23ff5500&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/hvmdmusic" title="HIVEMIND" target="_blank" style="color: #cccccc; text-decoration: none;">HIVEMIND</a> · <a href="https://soundcloud.com/hvmdmusic/mindcast-023-by-boryana" title="MINDCAST 023 by Boryana" target="_blank" style="color: #cccccc; text-decoration: none;">MINDCAST 023 by Boryana</a></div>',
      height: 300,
    },
    {
      name: 'MINDCAST 022 by Jacob Hertz',
      description: 'MINDCAST 022 is the first vinyl podcast that we have and it\'s made by the Georgian artist Jacob Hertz.',
      css: 'linear-gradient(to top, #5ee7df 0%, #b490ca 100%)',
      cover: 'Cover_MINDCAST022.jpg',
      frame: '<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/760028749&color=%23ff5500&auto_play=false&hide_related=true&show_comments=false&show_user=true&show_reposts=false&show_teaser=false&visual=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/hvmdmusic" title="HIVEMIND" target="_blank" style="color: #cccccc; text-decoration: none;">HIVEMIND</a> · <a href="https://soundcloud.com/hvmdmusic/mindcast-022-by-jacob-hertz" title="MINDCAST 022 by Jacob Hertz" target="_blank" style="color: #cccccc; text-decoration: none;">MINDCAST 022 by Jacob Hertz</a></div>',
      height: 300,
    },
  ]